# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

install! 'cocoapods', :deterministic_uuids => false
target 'MapDemoIOS' do
 pod 'AMapSearch'
 pod 'AMapLocation'
 pod 'AMapNavi'

end
