# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'

source 'https://git.coding.net/J_YC/JYCRepoSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'
# 解决重复生产UUID的警告/Users/admin/soft/develop/ios/BossCommonClass-master/BossCommonClass.podspec
install! 'cocoapods', :deterministic_uuids => false
target 'MapDemoIOS' do
 pod 'AMapSearch'
 pod 'AMapLocation'
 pod 'AMapNavi'

  
end
